// hwp_exec 도구 정의 하나. mcp/server.mjs(tools/list), aside/register.mjs(캐시 신선도), 테스트가 같이 쓴다.
// 설명은 실행 계약과 자주 쓰는 도우미를 담는다. 전체 도우미·범위·허용 메서드 목록은 hwp.help()가 돌려준다.
// SERVER_INSTRUCTIONS는 MCP initialize의 instructions(서버 사용 지침)로 나간다.
export const TOOL_SPEC = Object.freeze({
  name: 'hwp_exec',
  description: "Run an async JavaScript body against one HWP/HWPX document in the Jongi (종이) library. The only global is hwp: start with const h = await hwp.open(docId) (list ids with await hwp.docs()). Call await hwp.help() for every helper, scope, unit and the allowlisted rhwp API. " +
    "Read: hwp.paragraphs(h), hwp.tables(h), hwp.cells(h,{table}), hwp.nestedTables(h) and hwp.cells(h,{nested}) for tables inside a table cell (forms often put consent/member tables there), hwp.checkboxes(h,{scope?}), hwp.find(h,{query,includeCells:true}) (nested hits carry nested:{nested,row,col,paragraph}). " +
    "Write: hwp.setCell(h,{table|nested,row,col,text,splitLines?,format?:'inherit'|'plain'|charProps}), hwp.insertTextInCell(h,{table|nested,row,col,paragraph,offset?,text}), hwp.insertText(h,{paragraph,text,splitLines?}), hwp.replaceText(h,{find,replace,occurrence?,expectedCount?,scope?}), hwp.setCheckbox(h,{label,scope?,checked?,mark?,exclusive?}|{box}), hwp.format(h, scope, {bold,italic,underline,size,textColor,fontName}), hwp.paraFormat(h, scope, {alignment,lineSpacing,unit:'pt',spacingBefore}), hwp.splitParagraph, hwp.deleteText, hwp.replaceAll, hwp.createTable, hwp.insertRow, hwp.mergeCells, and hwp.api(h, method, ...args). " +
    "Look: hwp.snapshot(h,{pages:[0],inline:true}) attaches page PNGs to this result so you can see the page (max 4 per call; includes unsaved edits made earlier in the call); hwp.snapshot(h,{pages?}) writes per-page PDF+PNG files; hwp.exportPdf(h,{open?}) writes one PDF, open:true shows it in Preview. " +
    "Scopes: hwp.selectAll(), {paragraph,start?,end?}, {from,to}, {table,row,col}, {table}, {nested,row,col}, {nested}. Finish edits with await hwp.save(h). Coordinates are 0-based; re-read after structural edits. hwp.open(docId,{follow:false}) keeps the user's editor tab. One document per call; same docId reopens its handle. Edits after save are rejected. A failed hwp call fails the whole call, nothing is written, and the result carries error, code and details. Return a small value (<=64 KiB). No imports or filesystem.",
  inputSchema: { type: 'object', properties: { code: { type: 'string' }, timeoutMs: { type: 'integer', minimum: 1, maximum: 120000 } }, required: ['code'], additionalProperties: false },
});
export const SERVER_INSTRUCTIONS = [
  'Jongi (종이) edits HWP/HWPX documents in the local Jongi (종이) library through one tool, hwp_exec. Each call runs a JavaScript body with a single global hwp and works on one document.',
  'Workflow: hwp.docs() -> hwp.open(docId) -> read the structure -> edit -> look at the page -> hwp.save(h). Reading and looking can happen in the same call as the edit; hwp.save(h) must come last. If any hwp call fails, the whole call is rolled back and nothing is saved: read error, code and details, fix the code, and run it again.',
  'Read the structure first: hwp.paragraphs(h) for body text, hwp.tables(h) and hwp.cells(h,{table}) for top-level tables. Korean application forms often place a whole table inside one cell (consent tables, member lists). When a cell looks like it should contain rows but hwp.cells shows only a title, call hwp.nestedTables(h) and hwp.cells(h,{nested:N}). Address those cells as {nested,row,col} in hwp.setCell, hwp.insertTextInCell, hwp.replaceText scope, hwp.format scope and hwp.setCheckbox scope.',
  "Checkboxes: hwp.checkboxes(h,{scope?}) lists every box (□ unchecked; ■ ☑ ▣ ☒ checked) with its label, e.g. {box:3,checked:false,mark:'□',label:'동의함',nested:0,row:1,col:2}. Check one with hwp.setCheckbox(h,{label:'동의함',scope:{nested:0,row:1,col:2}}) or hwp.setCheckbox(h,{box:3}). The mark follows the box's paragraph, then the document, then ☑; pass mark:'■' to force one. exclusive:true unchecks the other boxes in the same paragraph (동의함 / 동의하지 않음 pairs). checked:false restores □.",
  "Text: arguments are one line; use splitLines:true on hwp.setCell or hwp.insertText for several lines. hwp.setCell keeps the cell's placeholder look by default; format:'plain' uses the document's Normal (바탕글) look, or pass charProps. Leave signature and seal cells empty unless asked; images are not edited.",
  'Look before and after editing: hwp.snapshot(h,{pages:[p],inline:true}) returns page images in the tool result (0-based pages, at most 4 per call, maxPx 1400 by default). It renders unsaved edits made earlier in the same call, so you can check the layout before hwp.save(h). hwp.snapshot without inline writes PDF and PNG files under ~/.lidge-hwp/exports; hwp.exportPdf(h) writes the whole document as one PDF, and hwp.exportPdf(h,{open:true}) opens it in Preview for the user. Rendering uses the bundled rhwp CLI, whose page breaks can differ slightly from the editor.',
  'Coordinates are 0-based and shift after splitting, inserting or deleting paragraphs, rows or columns: re-read before the next edit. Tables nested two levels deep, headers, footers and footnotes are outside the helpers.',
  "The user's editor tab follows the first edit; hwp.open(docId,{follow:false}) keeps it in place. If the result says reloadRequired, tell the user to reload the tab. After CLIENT_DEADLINE do not retry; check later with a read-only call.",
].join('\n');
